# To install the git pre-commit hook run:
#   pre-commit install
# To update the pre-commit hooks run:
#   pre-commit install-hooks
exclude: '^(.tox/|.*\.mustache$|.*conf.py$)'
repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes
      - id: check-hooks-apply

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: '(.*test/.*|.*test.py$|^setup.py$|^test_.*.py$)'
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-toml
      - id: check-yaml

  - repo: https://github.com/ambv/black
    rev: 25.1.0
    hooks:
      - id: black
        name: "Format code"
        exclude: '(.*test/.*|.*test.py$|^setup.py$|^test_.*.py$)'
        language_version: python3

  - repo: https://github.com/fsfe/reuse-tool
    rev: v5.0.2
    hooks:
    - id: reuse

  - repo: "https://github.com/asottile/blacken-docs"
    rev: "1.19.1"
    hooks:
      - id: "blacken-docs"
        name: "Format docs (blacken-docs)"
        args: ["-l", "64"]
        additional_dependencies:
          - "black==23.1.0"

  - repo: https://github.com/PyCQA/doc8
    rev: v1.1.2
    hooks:
      - id: doc8
        args:
          - '--max-line-length=90'
          - '--ignore=D001'

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: rst-backticks
        # exclude: ChangeLog\.rst$
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  - repo: https://github.com/myint/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        exclude: '(.*test/.*|.*test.py$|^setup.py$|^test_.*.py$)'
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-duplicate-keys
          - --remove-unused-variables

  - repo: https://github.com/PyCQA/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        exclude: '(.*test/.*|.*test.py$|^setup.py$|^test_.*.py$)'
        additional_dependencies: ["flake8-bugbear"]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args: ["-ll", "-q", "-c", "pyproject.toml"]
        files: src/
