codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 5%
        if_not_found: success
    changes: no

  precision: 2
  round: nearst
  range: 80...100

  notify:
    irc:
      default:
        server: chat.freenode.net
        channel: '##code-hell'
        branches: master
        threshold: 2
        message: null

ignore:
 - "bin/.*"
 - "test/.*"
 - ".tox/.*"
 - "*.rst"

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  # layout: "reach, diff, flags, tree"
  branches: null
  behavior: default
  require_changes: no
